# Generated by Django 3.1.3 on 2021-02-08 16:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaxLegislation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('photo_main', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('description', models.TextField(max_length=200)),
                ('docu_main', models.FileField(upload_to='docs/%Y/%m/%d/')),
                ('list_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
